meta_product_name: "Mediless"
meta_title: "Mediless - Se soigner grâce à soi-même "
meta_description: "Trouver des solutions naturelles pour vous aider à soigner des symptômes de la vie courante."
meta_image: "christin-hume-0MoF-Fe0w0A-unsplash.jpg" # should exist in `app/assets/images/`
